[projects.cd]
path = 'Source\CD_CI_Test Custom Device.lvproj'

[[build.steps]]
name = 'Build My Custom Device'
type = 'lvBuildAll'
project = '{cd}'

[[test.steps]]
name = 'Functional_Test'
type = 'lvVITester'
test_path='\Source\Tests\Unit\MyTestCase.lvclass'

[[test.steps]]
name = 'System_Test'
type = 'lvVITester'
test_path='\Source\Tests\Unit\SystemTestCase.lvclass'
